spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/customers"
    username: "root"
    password: "test123"
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html